### ISSUE TITLE
Client expiration date and multiple login 

### ISSUE THREAD

**Issue by UltimateABC** [firezone/firezone#1626]
Hi

Please add new features for clients configuration 

Add an option to set the multiple login or set max device login numbers

Add another option to set client expiration date, 

Thanks

**Comment by jamilbk** [comment]
Hi there, thanks for the request.

I'm not entirely sure what you're requesting here, but I our upcoming 1.0 release will address them. I'll ref that here and close this for now.

**Comment by UltimateABC** [comment]
Hi again

IP limitation option , could be defined if client tries to connect to server more than 1 device, their account be deactivated for a some specific time, such as 1 hour block to access or permanent deactivation.


Client Expiration date: when you define new client, you can set the date for deactivating config, for example make a client that disables after one month usage
