### ISSUE TITLE
Let's encrypt domain validation with DNS challenge

### ISSUE THREAD

**Issue by den-q** [firezone/firezone#1637]
Hello, It would be great if there will an option to use dns challenge  for let's encrypt.
thank you

**Comment by jamilbk** [comment]
Hi @den-q -- Firezone doesn't terminate SSL itself so you'll have more luck simply making the required changes to the `caddy` service in `$HOME/.firezone/docker-compose.yml` yourself. See if this is helpful: https://caddy.community/t/how-to-use-dns-provider-modules-in-caddy-2/8148

You could also terminate SSL with your proxy of choice and configure ACME there.
