### ISSUE TITLE
Firezone interface and firewall rules don't persist after reboot

### ISSUE THREAD

**Issue by jamilbk** [firezone/firezone#298]
As reported in #283, the `wg-firezone` interface and `firezone` netfilter table don't persist after a reboot.

Firezone should check to ensure these are enabled and configured properly on application startup.

**Comment by w202mg** [comment]
This feature is mostly expected by me. Yesterday accidentally rebooted the server and had to uninstall and install Firezone again. Number 2 is the possibility to set custom DNS server in config/disable it.

Hope to see these features soon.
