### ISSUE TITLE
Document device private key generation

### ISSUE THREAD

**Issue by MikeTsenatek** [firezone/firezone#746]
Hey,

would it be possible to allow an expert setting that experienced users can provide there own public key generated offline, so the security level is higher?

Best regards
Mike

**Comment by jamilbk** [comment]
@MikeTsenatek Thanks for the suggestion. We could certainly expose the `public_key` and `preshared_key` fields but need to think through this a bit more. A couple questions --

1. Would you want the preshared_key exposed as well?
2. In terms of expert setting, are you thinking this would apply to only admins, or would you prefer a config option `default['firezone']['wireguard']['allow_user_supplied_keys']` or a combo of the two?

**Comment by MikeTsenatek** [comment]
I think an Admin should never see or set the private key for an user. 
The idea with "default['firezone']['wireguard']['allow_user_supplied_keys']" is very good. 

Yeah, the PSK is also a good idea to set by an expert user.

Mike

**Comment by jamilbk** [comment]
@MikeTsenatek I see, so you'd need a way to classify certain users as "expert users" outside of the current Promote/Demote functionality for admins.

**Comment by MikeTsenatek** [comment]
Nope, I would only wrote at the device add page a warning that this is an expert setting.

:)

**Comment by grantwest** [comment]
Yes, private keys should be generated on the client device and never be sent to the server. The tools to make this user friendly don't exist yet though. Down the road firezone could have native apps that allow the user to bypass handling wireguard configs at all. An app for each platform that allows this workflow: user auth, generate client keypair, send pubkey to firezone server and get wireguard config, configure wireguard. 
An internet VPN service named [Mullvad](https://mullvad.net/en/download) has actually already built apps just like this, and they happen to be [open source](https://github.com/mullvad/mullvadvpn-app)

**Comment by jamilbk** [comment]
Thanks @grantwest! Yep, good point.

Just to clarify for anyone reading, Firezone private keys are generated in the device's browser (never the server) and never saved.

@MikeTsenatek We'll be starting on client applications soon and I'm not sure this feature would make sense after the re-architecture that will entail. Keys would be generated in the client, public keys sent to Firezone upon login, and rotated automatically periodically. Devices would become ephemeral essentially.

~~We could support this in 0.5.0, keeping in mind the above going forward.~~

Edit: With the number of changes coming to devices with the introduction of client apps, and the fact that device keys are *already* generated on the device, going to hold on this.

**Comment by MikeTsenatek** [comment]
Sounds good. 

Maybe it should be more clear in the documentation. 

So that is fine for me!
